server:
  port: 8011
 
spring:
  application:
   name: user-service
 
eureka:
  instance:
    prefer-ip-address: true
    instance-id: user-microservice-instance
  client:
    register-with-eureka: true # 유레카 서비스에 (자신을) 등록 여부
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
